proxy:
  chp:
    networkPolicy:
      enabled: false
  service:
    nodePorts:
      http: 32000
prePuller:
  hook:
    enabled: false
  continuous: 
    enabled: false 
hub: 
  nodeSelector:
    kubernetes.io/hostname: "kepler"
singleuser:
  cmd: null
  image:
    name: jupyter/minimal-notebook
    tag: latest
  profileList:
  - display_name: "Minimal environment"
    description: "To avoid too much bells and whistles: Python."
    default: true
    kubespawner_override:
      node_selector:
        kubernetes.io/hostname: "kepler"
  - display_name: "PyTorch GPU Server"
    description: "Spawns a notebook server with access to a GPU and PyTorch"
    kubespawner_override:
      image: quay.io/jupyter/pytorch-notebook:cuda12-python-3.12.10
      extra_pod_config:
        runtimeClassName: nvidia
      node_selector: 
        kubernetes.io/hostname: "kepler"
      extra_resource_limits:
        nvidia.com/gpu: "1"
      extra_resource_guarantees:
        nvidia.com/gpu: "1"
  storage:
    capacity: 60Gi
    extraVolumes:
    - name: shm-volume
      emptyDir:
        medium: Memory
    extraVolumeMounts:
    - name: shm-volume
      mountPath: /dev/shm
  extraFiles:
    jupyter_notebook_config.json:
      mountPath: /etc/jupyter/jupyter_notebook_config.json
      data:
        MappingKernelManager:
          cull_idle_timeout: 1200
          cull_interval: 120
          cull_connected: true
          cull_busy: false
