[project]
authors = ["dimitris.lygkonis <dimitris.lygkonis@iccs.gr>"]
channels = ["conda-forge"]
name = "platform-source"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.9.19"
pixi-pycharm = ">=0.0.8,<0.0.9"
gdal = "==3.7.3"
rasterio = "==1.3.9"

[pypi-dependencies]
ray = { version = "==2.36.0", extras = ["serve"] }
mlflow = "==2.20.2"
xgboost = "==2.1.3"
scikit-learn= "==1.5.2"
numpy = "==1.26.4"
tensorflow = "==2.17.1"
fastapi = "==0.110.0"
pydantic = "==2.8.0"
python-multipart = ">=0.0.20, <0.0.21"
smart-open = ">=7.1.0, <8"
eumdac = ">=3.0.0, <4"
tqdm = ">=4.67.1, <5"
apache-airflow = ">=2.10.5, <3"
cdsapi = ">=0.7.4"
xarray = { version = ">=2024.7.0, <2025"}
earthaccess = ">=0.11.0, <0.12"
haversine = ">=2.9.0, <3"
boto3 = ">=1.36.23, <2"
netcdf4 = ">=1.7.2, <2"
h5netcdf = ">=1.5.0, <2"
denseweight = "==0.1.2"
imbalance-metrics = "==0.0.6"
pandas = "==2.2.3"
scipy = ">=1.13.1"
kubernetes = ">=32.0.1, <33"
joblib = "==1.4.2"
attrs = "*"
