[project]
authors = ["dimitris.lygkonis <dimitris.lygkonis@iccs.gr>"]
channels = ["conda-forge"]
name = "Precipitation Model Production"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.9.21"
gdal = "==3.7.3"

[pypi-dependencies]
rasterio = "==1.3.11"
pandas = "==2.0.3"
numpy = "==1.26.4"
mlflow = "==2.20.2"
pydantic = "==2.8.0"
boto3 = "==1.36.22"

