[project]
authors = ["dimitris.lygkonis <dimitris.lygkonis@iccs.gr>"]
channels = ["conda-forge"]
description = "Active fires model development."
name = "active_fires"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.9.21"
gdal = "==3.7.3"

[pypi-dependencies]
mlflow = { version = "==2.20.2"}
pydantic = "==2.10.6"
pydantic-settings = "==2.7.1"
hyperopt = "==0.2.7"
boto3 = "==1.36.22"
tensorflow = { version = "==2.17.1", extras = ["and-cuda"] }
eumdac = ">=3.0.0, <4"
tqdm = ">=4.67.1, <5"