[project]
authors = ["dimitris.lygkonis <dimitris.lygkonis@iccs.gr>"]
channels = ["conda-forge"]
name = "Precipitation model development."
platforms = ["linux-64"]
version = "0.1.0"

[tasks]


[dependencies]
python = "==3.9.21"


[pypi-dependencies]
mlflow = "==2.20.2"
boto3 = "==1.7.84"
pandas = "==2.0.3"
numpy = "==1.26.4"
denseweight = "==0.1.2"
imbalance-metrics = "==0.0.6"
scipy = "==1.10.1"
tqdm= "==4.67.1"
xgboost = "==2.1.4"
pydantic = "==2.10.6"
rasterio = "==1.3.11"
joblib = "==1.4.2"
