[project]
authors = ["dimitris.lygkonis <dimitris.lygkonis@iccs.gr>"]
channels = ["conda-forge"]
name = "Carbon monoxide production."
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.9.21"
gdal = "==3.7.3"


[pypi-dependencies]
cdsapi = "==0.7.4"
xarray = "==2024.7.0"
earthaccess = "==0.11.0"
haversine = "==2.9.0"
joblib = ">=1.4.2, <2"
mlflow = "==2.20.2"
boto3 = "==1.36.22"
netcdf4 = "==1.7.2"
h5netcdf = "==1.5.0"
